### ISSUE TITLE
Issues installing on WSL2 (Windows 10)

### ISSUE THREAD

**Issue by macabuag** [OasisLMF/OasisEvaluation#18]
For both the Platform (OasisEvaluation) and the MDK I receive the following errors when trying to install oasislmf within Windows Subsystem for Linux (WSL2 Ubuntu 20.04). I do not receive this error when installing natively on an Ubuntu machine.

`Failed to build shutilwhich rtree future pandocfilters tornado python-slugify pyrsistent`

See screenshots with errors attached
[Issue-WSL2 installation.pdf](https://github.com/OasisLMF/OasisEvaluation/files/5343570/Issue-WSL2.installation.pdf)

Does anyone know how I can resolve this for WSL installation, and complete the installation of oasislmf?

**Comment by benhayes21** [comment]
@KamalCharles - can you please try to recreate this issue on WSL2?

**Comment by KamalCharles** [comment]
Hi @macabuag , The solution that I found is to download `Anaconda Python3` Distribution as it has many relevant dependencies pre-built in. 

Below are the steps to get `OasisEvaluation` working with WSL2 - Ubuntu 20.04

Inside WSL2 Ubuntu 20.04 Terminal

1.  `sudo apt update && sudo apt install git docker docker-compose && sudo apt install python3-pip `

**__Anaconda-3-5.2.0-Linux 64 Bit__**

2.  `wget https://repo.continuum.io/archive/Anaconda3-5.2.0-Linux-x86_64.sh`

3.  `bash Anaconda3-5.2.0-Linux-x86_64.sh`

**After Installation**
Change bashrc varaiable to point to Anaconda
5.  `export PATH=~/anaconda3/bin:$PATH`

**Install missing packages**
6. `pip install msgpack && pip install --upgrade pip` 
8. `conda install libspatialindex && conda remove llvmlite --force && pip install llvmlite`


**Docker for WSL2**
(Docker for Desktop must be installed and integrated with your WSL2 -Ubuntu 20.04) 

Install Docker for Desktop from Microsoft store 
Enable WSL Integration from under:   `Settings > Resources > Ubuntu -20.04 > Apply & Restart`

$ `git clone https://github.com/OasisLMF/OasisEvaluation.git`
$ `cd OasisEvaluation `
$ `./install.sh `
$ `docker ps -a`
$ `oasislmf version`

**Comment by KamalCharles** [comment]
Hi @macabuag , I managed to recreate the problem. I found that using  `Anaconda Python3` Distribution allows easier installation on WSL2 as there are many relevant dependencies pre-built in. 

Below are the steps to get `OasisEvaluation` working with WSL2 - Ubuntu 20.04

Inside WSL2 Ubuntu 20.04 Terminal

1.  `sudo apt update && sudo apt install git docker docker-compose && sudo apt install python3-pip `

**__Anaconda-3-5.2.0-Linux 64 Bit__**

2.  `wget https://repo.continuum.io/archive/Anaconda3-5.2.0-Linux-x86_64.sh`

3.  `bash Anaconda3-5.2.0-Linux-x86_64.sh`

**After Installation**
Change bashrc varaiable to point to Anaconda
4.  `export PATH=~/anaconda3/bin:$PATH`

**Install missing packages**
5. `pip install msgpack && pip install --upgrade pip` 
6. `conda install libspatialindex && conda remove llvmlite --force && pip install llvmlite`


**Docker for WSL2**
(Docker for Desktop must be installed and integrated with your WSL2 -Ubuntu 20.04) 

Install Docker for Desktop from Microsoft store 
Enable WSL Integration from under:   `Settings > Resources > Ubuntu -20.04 > Apply & Restart`

$ `git clone https://github.com/OasisLMF/OasisEvaluation.git`
$ `cd OasisEvaluation `
$ `./install.sh `
$ `docker ps -a`
$ `oasislmf version`

**Comment by benhayes21** [comment]
Hi @macabuag - can you confirm that this is ok for you? Then we will close the issue.

Thanks,
Ben

**Comment by macabuag** [comment]
@benhayes21, thanks for looking to this. I will be able to test this solution out towards the end of this week, so I will let you know.

Thanks again,

**Comment by macabuag** [comment]
Thanks again for looking ito this. Following the steps above, the installation seems to proceed ok without error. Thanks!

However, now when I attempt to run an analysis via the platform I receive the following error.

![image](https://user-images.githubusercontent.com/31392092/101194275-aeefc000-3655-11eb-917d-bf9c0bbf80ef.png)

I have successfully run analyses previously (on other installations of the Platform), but have never seen this error before. I am attempting to load loc & acc files from the OasisPiWind folder:
\\wsl$\Ubuntu-20.04\...\OasisEvaluation\OasisPiWind\tests\inputs 

Is this related to the installation procedure or a new and separate issue? Happy to close this issue and open a new one if so.

Thanks again for your help,

Cheers

**Comment by KamalCharles** [comment]
Hi @macabuag , unfortunately I was unable to re-create this error within my environment. I think this could be an out-dated version of the UI within Oasis Evaluation. I'm going to take another look and will get back to ypu/

**Comment by benhayes21** [comment]
Hi @macabuag - we think that this error was actually introduced in a recent release but has since been fixed in v1.8.2 of the Oasis UI. Closing this off for now.
