### ISSUE TITLE
Opening UI error 500

### ISSUE THREAD

**Issue by clem9123** [OasisLMF/OasisEvaluation#26]
After installing Oasis evaluation (following the youtube tutoriel), I tried to open oasis ui at "http://localhost:8080/app/BFE_RShiny" but I get this error :

"Error
Status code: 500
Message: Container did not respond in time
Stack Trace:
eu.openanalytics.shinyproxy.ShinyProxyException: Container did not respond in time"

Do you know why and how to solve this problem ?

Thanks in advance

**Comment by sambles** [comment]
Hello @clem9123 I'm not sure why ShinyProxy is failing to create the UI container, could something else be bound on the `8080` port?    (also which OS / distribution and version are you running OasisEvaluation under?)

Theres a similar issue here: 
https://github.com/openanalytics/shinyproxy/issues/202

**Comment by sambles** [comment]
Actually this issue seems a better match: https://support.openanalytics.eu/t/container-unresponsive-and-container-did-not-respond-in-time/1128 

It might be an issue with the docker.socket that Shiny uses to spawn the UI container. Can you link the full trace for the  `shiny_proxy` container?

**Comment by clem9123** [comment]
Technically I succeded into running it but only once in a while, every other times I keep getting this 500 error.
For now my best solution is to run until it works
I'll go and see the issues you linked
Thank you very much

Is this what you meant by the full trace ? :

> (sambles - edited) Attached trace as txt
[ShinyProxy_trace.txt](https://github.com/OasisLMF/OasisEvaluation/files/6623031/ShinyProxy_trace.txt)

**Comment by sambles** [comment]
Hi @clem9123  Thanks for posting the trace, I've push the contents into a txt file. 

No obvious errors are jumping out to me (other than the ShinyProxy communication issue with the UI container)  
Can you try running the UI image as a stand alone container and see if that works? 


1. Create a new compose file and run that in parallel with the OasisEvaluation containers. 

> #### oasisUI-stand-alone.yml
> ```
> version: '3' 
> services:
>   user-interface:
>     network_mode: host
>     image: coreoasis/oasisui_app:1.9.0
>     environment:
>      - API_IP=localhost
>      - API_PORT=8000
>      - API_VERSION=v1
>      - API_SHARE_FILEPATH=./downloads
>      - OASIS_ENVIRONMENT=oasis_localhost  
> ```

2. Run using `docker-compose -f oasisUI-stand-alone.yml up -d`

3. Access the new container via [http://localhost:3838/](http://localhost:3838/)

**Comment by benhayes21** [comment]
closing - old
