### ISSUE TITLE
localhost:8080 - Issue- "API is down. Please try again later"

### ISSUE THREAD

**Issue by isha602** [OasisLMF/OasisEvaluation#31]
I am trying to run the UI of OasisLMF

1) I was able to run the command ./install.sh successfully. When I tried to access the localhost:8080(Rshiny) repository, I am facing the issue of "API is down. Please try again later". 

2) I was able to access the localhost:8000 (API Swagger UI)

Attaching the screenshot of the issue:

![image](https://user-images.githubusercontent.com/66596750/179838928-0511273f-2f6c-4f16-a8af-e964d3a07205.png)

Please help to resolve this issue.

**Comment by stephendragoni** [comment]
I am having the same issue. Did you get it resolved?

**Comment by OdabasiOmer** [comment]
I have the same issue on Linux. All docker containers seem to be up and running but I cant access any of the platforms (API, admin, or the other). The weird thing is it worked at first, Then stopped working once I closed the browser and wanted to open/re-log on.

![11111](https://user-images.githubusercontent.com/37015767/196119421-6af40991-d49a-4c0a-8a1a-9695ba405849.png)

Here are the versions I'm using.

![2222](https://user-images.githubusercontent.com/37015767/196119456-abbe977f-464b-4c38-b36a-b4b0252f4a64.png)

Would appreciate any feedback on this!

Regards.

**Comment by sambles** [comment]
Hi @OdabasiOmer thanks for the bug report,


I've tried to recreate this using similar steps (like closing the browser and re-running the `./install.sh`) 
However, I didn't hit the issue on Linux, were there other steps in between like restarting the laptop/pc ?  

Attaching the server logs should help us with troubleshooting.  
Can you run `docker logs  oasisevaluation-server-1 &> server_docker_logs.txt`  and link the generated file **server_docker_logs.txt** to this issue?

**Comment by OdabasiOmer** [comment]
Hi, @sambles. Many thanks for your quick turnaround on the issue. Unfortunately, I have already wiped everything and decided to try out "OasisPlatform" instead. I managed to set that one up! 

On a somewhat unrelated subject, I would like to ask if there's a fast track to introducing a new model by simply supplying the "oasislmf.json" settings file which contains paths (in local machine) to all relevant files/dictionaries/data for importing instead of adding individual CSVs one by one?

Many thanks in advance!

**Comment by b-cil** [comment]
Same error on OasisEvaluation...

The output of the command is :

Error: No such container: oasisevaluation-server-1

**Comment by sambles** [comment]
Hi all, the pull request above removes the [shinyproxy](https://www.shinyproxy.io/) container, this simplifies the docker networking and should avoid the `API is down. Please try again later` error. 

If you're still hitting problems, after a fresh `git pull`, please update this issue and we'll reopen

**Comment by b-cil** [comment]
hello @sambles ,

thank you for the quick response ! couldn't made it through the git pull had to erase everything and start all other again...

http://localhost:8080/app/BFE_RShiny not working it replies a Not Found

running same command as previous the error is the same :
Error: No such container: oasisevaluation-server-1

install.sh
```
export VERS_MDK=1.26.3
export VERS_API=1.26.3
export VERS_WORKER=1.26.3
export VERS_PIWIND=1.26.3
export VERS_UI=1.11.4
GIT_PIWIND=OasisPiWind
```

docker ps output :
```
68855e284e69   portainer/portainer:latest      "/portainer"             15 minutes ago   Up 24 seconds   0.0.0.0:8001->8001/tcp, :::8001->8001/tcp, 8000/tcp, 0.0.0.0:9000->9000/tcp, :::9000->9000/tcp                                                        oasisevaluation_portainer_1
0c26af4613c1   coreoasis/api_server:1.26.3     "startup wait-for-se…"   16 minutes ago   Up 15 minutes   8000/tcp                                                                                                                                              oasisevaluation_worker-monitor_1
2af4af732b84   coreoasis/api_server:1.26.3     "startup ./wsgi/run-…"   16 minutes ago   Up 15 minutes   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp                                                                                                             oasisevaluation_server_1
11280097ee12   iserko/docker-celery-flower     "flower --port=5555 …"   16 minutes ago   Up 15 minutes   0.0.0.0:5555->5555/tcp, :::5555->5555/tcp                                                                                                             oasisevaluation_flower_1
93ec7f88ca1d   coreoasis/model_worker:1.26.3   "/bin/sh -c ./startu…"   16 minutes ago   Up 15 minutes                                                                                                                                                         oasisevaluation_worker_1
7b6e7b3f6c51   coreoasis/oasisui_app:1.11.4    "R -e oasisui::runOa…"   16 minutes ago   Up 16 minutes   0.0.0.0:8080->3838/tcp, :::8080->3838/tcp                                                                                                             oasisui_app
c35aea1bceb3   postgres                        "docker-entrypoint.s…"   16 minutes ago   Up 16 minutes   5432/tcp                                                                                                                                              oasisevaluation_celery-db_1
2d44d136f68f   rabbitmq:3.8.14-management      "docker-entrypoint.s…"   16 minutes ago   Up 16 minutes   4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, :::5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp, :::15672->15672/tcp   oasisevaluation_rabbit_1
e886c37ee6fa   postgres                        "docker-entrypoint.s…"   16 minutes ago   Up 16 minutes   5432/tcp                                                                                                                                              oasisevaluation_server-db_1
```

I have changed your command to `docker logs oasisevaluation_server_1 &> server_docker_logs.txt`

the following output occurs
```
2022-10-19 19:58:39 +0000] [66] [INFO] Booting worker with pid: 66
[2022-10-19 19:58:39 +0000] [67] [INFO] Booting worker with pid: 67
[2022-10-19 19:58:39 +0000] [68] [INFO] Booting worker with pid: 68
[2022-10-19 19:58:39 +0000] [69] [INFO] Booting worker with pid: 69
[2022-10-19 19:58:39 +0000] [70] [INFO] Booting worker with pid: 70
INFO 2022-10-19 19:58:40,845 middleware 65 140054724812800 ^[[36mGET /healthcheck/^[[0m
DEBUG 2022-10-19 19:58:40,845 middleware 65 140054724812800 ^[[36m{'Host': 'server:8000', 'User-Agent': 'curl/7.81.0', 'Accept': 'application/json'}^[[0m
DEBUG 2022-10-19 19:58:40,845 middleware 65 140054724812800 ^[[36mb''^[[0m
INFO 2022-10-19 19:58:40,845 middleware 65 140054724812800 ^[[36mGET /healthcheck/ - 200^[[0m
DEBUG 2022-10-19 19:58:40,845 middleware 65 140054724812800 ^[[36m{'Content-Type': 'application/json', 'Allow': 'GET'}^[[0m
DEBUG 2022-10-19 19:58:40,845 middleware 65 140054724812800 ^[[36mb'{"status":"OK"}'^[[0m
INFO 2022-10-19 20:10:07,276 middleware 64 140054724812800 ^[[36mGET /^[[0m
DEBUG 2022-10-19 20:10:07,277 middleware 64 140054724812800 ^[[36m{'Host': 'localhost:8000', 'Connection': 'keep-alive', 'Sec-Ch-Ua': '"Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99>
DEBUG 2022-10-19 20:10:07,277 middleware 64 140054724812800 ^[[36mb''^[[0m
INFO 2022-10-19 20:10:07,277 middleware 64 140054724812800 ^[[36mGET / - 200^[[0m
INFO 2022-10-19 20:10:08,063 middleware 67 140054724812800 ^[[36mGET /?format=openapi^[[0m
DEBUG 2022-10-19 20:10:08,064 middleware 67 140054724812800 ^[[36m{'Host': 'localhost:8000', 'Connection': 'keep-alive', 'Sec-Ch-Ua': '"Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99>
DEBUG 2022-10-19 20:10:08,064 middleware 67 140054724812800 ^[[36mb''^[[0m
INFO 2022-10-19 20:10:08,064 middleware 67 140054724812800 ^[[36mGET /?format=openapi - 200^[[0m
```

best,
Pierre
