### ISSUE TITLE
unable to install cloned repository on mac - getting a pathspec error 

### ISSUE THREAD

**Issue by PatrickStranks** [OasisLMF/OasisEvaluation#41]
## Issue Description
When I try to run the install.sh command i get the error: pathspec '1.27.1' did not match any file(s) known to git. I have no idea why this is happening as I believe i've followed all the previous steps correctly.

Maybe it's because i'm using a mac but I'm very new to working through command lines so it could be something very basic. Any advice as to why this is happening would be very much appreciated :)
## Steps to Reproduce (Bugs only)

1. Just following the install process 
2.
3.

## Version / Environment information
Mac OS
1.27.1

**Comment by PatrickStranks** [comment]
> ## Issue Description

When I try to run the install.sh command i get the error: pathspec '1.27.1' did not match any file(s) known to git. I have no idea why this is happening as I believe i've followed all the previous steps correctly. 

Maybe it's because i'm using a mac but I'm very new to working through command lines so it could be something very basic. Any advice as to why this is happening would be very much appreciated :)

**Comment by sambles** [comment]
Thanks for the issue! Problem was in the installation script, it should be fixed with

**Comment by sambles** [comment]
Thanks for the issue report!  
The problem was in the installation script and should be fixed with  https://github.com/OasisLMF/OasisEvaluation/pull/42 

If you pull the latest commit and rerun the install script it should work:
```
git pull
./install.sh
``` 

I'll leave this open for the moment, just in case that didn't fix the problem
